name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.air.toml'
      - '.gitignore'
      - 'docker-compose.yml'
      - 'README.md'

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ci]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        id: semantic
        # https://github.com/cycjimmy/semantic-release-action
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-non-release-image:
    name: Build and Push Non-Release Image
    uses: ./.github/workflows/_build-and-push-image.yml
    needs: [ci, release]
    if: needs.release.outputs.new_release_published != 'true'
    permissions:
      contents: read
      attestations: write
      packages: write
      id-token: write
    with:
      tags: |
        type=sha,format=short,prefix=
        type=raw,value=latest

  build-and-push-release-image:
    name: Build and Push Release Image
    uses: ./.github/workflows/_build-and-push-image.yml
    needs: [ci, release]
    if: needs.release.outputs.new_release_published == 'true'
    permissions:
      contents: read
      attestations: write
      packages: write
      id-token: write
    with:
      tags: |
        type=raw,value=v${{ needs.release.outputs.new_release_version }}
        type=sha,format=short,prefix=
        type=raw,value=latest

  argocd-gitops:
    needs: [build-and-push-release-image, release]
    if: needs.release.outputs.new_release_published == 'true'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/_argocd-gitops.yml
    secrets: inherit
    with:
      docker-image-tag: ${{ needs.build-and-push-release-image.outputs.image-tag }}