name: Create and Push Docker Image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push-docker:
    uses: ./.github/workflows/_build-and-push-image.yml
    with:
      tags: |
        type=sha,format=short,prefix=
        type=raw,value=latest
